export const REQUEST_TYPE = '_REQUEST';
export const SUCCESS_TYPE = '_SUCCESS';
export const FAILURE_TYPE = '_FAILURE';
export const SET_LEADER_TYPE = 'SET_LEADER_TYPE';
export const LOGIN_TYPE = 'LOGIN';
export const LOGOUT_TYPE = 'LOGOUT_TYPE';
export const GET_USER_TYPE = 'GET_USER_TYPE';

// Display for responsive 
export const SET_PAGE_DISPLAY_MODE ='SET_PAGE_DISPLAY_MODE';

// Action type for work order on job summary
export const SELECT_JOBS = 'SELECT_JOBS';
export const FETCH_LIST_JOBS_ASSIGNMENT = 'FETCH_LIST_JOBS_ASSIGNMENT';
export const FETCH_JOB_DETAIL = 'FETCH_JOB_DETAIL';
export const FETCH_EQUIPMENT_VALUE_GET = 'FETCH_EQUIPMENT_VALUE_GET';
export const EQUIPMENT_VALUE_SUBMIT = 'EQUIPMENT_VALUE_SUBMIT';
export const SELECTED_JOB = 'SELECTED_JOB';
export const UNHANDOVER_JOB = 'UNHANDOVER_JOB';
export const HANDOVER_JOB = 'HANDOVER_JOB';
export const FETCH_JOB_REPORT = 'FETCH_JOB_REPORT';

// Action type for assignment on job summary
export const FETCH_LIST_MECHANIC = 'FETCH_LIST_MECHANIC';
export const ASSIGN_JOB ='ASSIGN_JOB';
export const UNASSIGN_JOB ='UNASSIGN_JOB';
export const SUMMARY = 'SUMMARY';

// Action type for problem log on job summary
export const FETCH_MASTER_DATA_PROBLEM_LOG = 'FETCH_MASTER_DATA_PROBLEM_LOG';
export const COUNT_BY_SPV = 'COUNT_BY_SPV';
export const LIST_BY_SPV = 'LIST_BY_SPV';
export const GET_DETAIL_PROBLEMLOG = 'GET_DETAIL_PROBLEMLOG';
export const SELECTED_PROBLEMLOG = 'SELECTED_PROBLEMLOG';
export const SUBMIT_PROBLEMLOG = 'SUBMIT_PROBLEMLOG';
export const REJECT_PROBLEMLOG = 'REJECT_PROBLEMLOG';
export const LIST_WORKCENTER_PERCENTAGE = 'LIST_WORKCENTER_PERCENTAGE';
export const LIST_ACHIEVEMENT_PERCENTAGE = 'LIST_ACHIEVEMENT_PERCENTAGE';
export const LIST_PROBLEMLOG_MONITORING = 'LIST_PROBLEMLOG_MONITORING';
export const CLOSE_PROBLEMLOG_MONITORING = 'CLOSE_PROBLEMLOG_MONITORING';
export const UPDATE_PROBLEMLOG_APPROVAL = 'UPDATE_PROBLEMLOG_APPROVAL';
export const DOWNLOAD_REPORT_PROBLEM_LOG = 'DOWNLOAD_REPORT_PROBLEM_LOG';

// Action type for tracking on job summary
export const STAGING_INFO = 'STAGING_INFO';
export const ASSIGN_TRACKING = 'ASSIGN_TRACKING';

// Action type for periodic inspection
export const FETCH_FORM_UNIT_MODEL = 'FETCH_FORM_UNIT_MODEL';
export const GET_CHECKSHEET_VALUE = 'GET_CHECKSHEET_VALUE';
export const APPROVE_PERIODIC_INSPECTION = 'APPROVE_PERIODIC_INSPECTION';
export const SUBMIT_PERIODIC_INSPECTION = 'SUBMIT_PERIODIC_INSPECTION';
export const DOWNLOAD_REPORT_PI = 'DOWNLOAD_REPORT_PI';

// Action type for backlog
export const SUMMARY_BACKLOG = 'SUMMARY_BACKLOG';
export const LIST_BACKLOG = 'LIST_BACKLOG';
export const DETAIL_BACKLOG = 'DETAIL_BACKLOG';
export const MASTER_DATA_BACKLOG = 'MASTER_DATA_BACKLOG';
export const GET_SPECIFIC_OBJECT_CHOICES = 'GET_SPECIFIC_OBJECT_CHOICES';
export const VALIDATE_SPARE_PART = 'VALIDATE_SPARE_PART';
export const SEARCH_SPARE_PART = 'SEARCH_SPARE_PART';
export const APPROVE_BES = 'APPROVE_BES';
export const REJECT_BES = 'REJECT_BES';
export const SUBMIT_BACKLOG = 'SUBMIT_BACKLOG';
export const APPROVE_BMS = 'APPROVE_BMS';
export const BMS_ACHIEVEMENT = 'BMS_ACHIEVEMENT';
export const BMS_ACHIEVEMENT_BY_WORK_CENTER = 'BMS_ACHIEVEMENT_BY_WORK_CENTER';
export const BMS_ACHIEVEMENT_BY_UNIT_MODEL = 'BMS_ACHIEVEMENT_BY_UNIT_MODEL';
export const BMS_ACHIEVEMENT_BY_UNIT_CODE = 'BMS_ACHIEVEMENT_BY_UNIT_CODE';
export const BMS_ACHIEVEMENT_DETAIL = 'BMS_ACHIEVEMENT_DETAIL';
export const BMS_WEB_SUBMIT = 'BMS_WEB_SUBMIT';
export const DOWNLOAD_REPORT_BACKLOG = 'DOWNLOAD_REPORT_BACKLOG';