export const MENU = {
    LOGIN: '/webdca/',
    DASHBOARD: '/webdca/dashboard',
    JOBS:'/webdca/jobs',
    JOBS_REPORT:'/webdca/jobs/report',
    JOBS_SUMMARY:'/webdca/jobs/summary',
    DETAIL_PI:'/webdca/jobs/summary/detailpi/',
    DETAIL_PROBLEMLOG:'/webdca/jobs/summary/detailpi/detailproblemlog/',
    SETTING:'/webdca/setting',
    PROBLEMLOG_MONITORING:'/webdca/problemlog',
    PROBLEMLOG_MONITORING_JOB_TYPE:'/webdca/problemlog/:workCenterCode',
    PROBLEMLOG_MONITORING_JOB_LIST:'/webdca/problemlog/:workCenterCode/:jobType/list-monitoring',
    PROBLEMLOG_MONITORING_DETAIL:'/webdca/problemlog/:workCenterCode/:jobType/:Id',
    LOGOUT:'/webdca/logout',
    BACKLOG:'/webdca/backlog/',
    BACKLOG_MONITORING:'/webdca/backlog/monitoring/',
    BACKLOG_MONITORING_UNIT_MODEL:'/webdca/backlog/monitoring/:workcenter',
    BACKLOG_MONITORING_UNIT_CODE:'/webdca/backlog/monitoring/:workcenter/:unitModel',
    BACKLOG_MONITORING_LIST_JOB:'/webdca/backlog/monitoring/:workcenter/:unitModel/:unitcode',
    
}